services:
  eureka:
    image: ${HS_EUREKA_IMAGE:-mhws/hs-eureka:latest}
    ports:
      - ${HS_EUREKA_PORT:-8761}:8761

  gateway:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - ${HS_GATEWAY_PORT:-8762}:8762
    environment:
      HS_GATEWAY_EUREKA_URI: http://eureka:8761/eureka

  postgres:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      HS_USER_POSTGRES_DATABASE: db_user
      HS_USER_POSTGRES_USERNAME: ${HS_USER_POSTGRES_USERNAME}
      HS_USER_POSTGRES_PASSWORD: ${HS_USER_POSTGRES_PASSWORD}
      HS_CMS_POSTGRES_DATABASE: db_cms
      HS_CMS_POSTGRES_USERNAME: ${HS_CMS_POSTGRES_USERNAME}
      HS_CMS_POSTGRES_PASSWORD: ${HS_CMS_POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./services/postgres/entrypoint/:/docker-entrypoint-initdb.d/

  liquibase-user:
    image: liquibase/liquibase:4.24-alpine
    depends_on:
      - postgres
    environment:
      LIQUIBASE_COMMAND_USERNAME: ${HS_USER_POSTGRES_USERNAME}
      LIQUIBASE_COMMAND_PASSWORD: ${HS_USER_POSTGRES_PASSWORD}
      LIQUIBASE_COMMAND_URL : jdbc:postgresql://postgres:5432/db_user
    volumes:
      - ./services/liquibase/changelog:/liquibase/changelog
      - ./services/liquibase/liquibase.user.properties:/liquibase/liquibase.properties
    command: --defaults-file=/liquibase/liquibase.properties update

  liquibase-cms:
    image: liquibase/liquibase:4.24-alpine
    depends_on:
      - postgres
    environment:
      LIQUIBASE_COMMAND_USERNAME: ${HS_CMS_POSTGRES_USERNAME}
      LIQUIBASE_COMMAND_PASSWORD: ${HS_CMS_POSTGRES_PASSWORD}
      LIQUIBASE_COMMAND_URL : jdbc:postgresql://postgres:5432/db_cms
    volumes:
      - ./services/liquibase/changelog:/liquibase/changelog
      - ./services/liquibase/liquibase.cms.properties:/liquibase/liquibase.properties
    command: --defaults-file=/liquibase/liquibase.properties update

  hs-user:
    image: ${HS_USER_IMAGE:-mhws/hs-user:latest}
    environment:
      HS_USER_EUREKA_URI: http://eureka:8761/eureka
      HS_USER_DATASOURCE_HOST: postgres
      HS_USER_DATASOURCE_PORT: 5432
      HS_USER_DATASOURCE_DATABASE: db_user
      HS_USER_DATASOURCE_USERNAME: ${HS_USER_POSTGRES_USERNAME}
      HS_USER_DATASOURCE_PASSWORD: ${HS_USER_POSTGRES_PASSWORD}
      HS_USER_JWT_SECRET_KEY: ${HS_USER_JWT_SECRET_KEY}
      HS_USER_JWT_EXPIRATION: ${HS_USER_JWT_EXPIRATION}

  hs-cms:
    image: ${HS_CMS_IMAGE:-mhws/hs-cms:latest}
    environment:
      HS_CMS_EUREKA_URI: http://eureka:8761/eureka
      HS_CMS_DATASOURCE_HOST: postgres
      HS_CMS_DATASOURCE_PORT: 5432
      HS_CMS_DATASOURCE_DATABASE: db_cms
      HS_CMS_DATASOURCE_USERNAME: ${HS_CMS_POSTGRES_USERNAME}
      HS_CMS_DATASOURCE_PASSWORD: ${HS_CMS_POSTGRES_PASSWORD}

volumes:
  postgres-data:
