services:
  eureka:
    image: ${HS_EUREKA_IMAGE:-mhws/hs-eureka:latest}
    ports:
      - ${HS_EUREKA_PORT:-8375}:8761

  postgres:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-example}
      HS_USER_POSTGRES_DATABASE: db_user
      HS_USER_POSTGRES_USERNAME: ${HS_USER_POSTGRES_USERNAME:-hs}
      HS_USER_POSTGRES_PASSWORD: ${HS_USER_POSTGRES_PASSWORD:-example}
      HS_CMS_POSTGRES_DATABASE: db_cms
      HS_CMS_POSTGRES_USERNAME: ${HS_CMS_POSTGRES_USERNAME:-hs}
      HS_CMS_POSTGRES_PASSWORD: ${HS_CMS_POSTGRES_PASSWORD:-example}
      HS_BOX_POSTGRES_DATABASE: db_box_office
      HS_BOX_POSTGRES_USERNAME: ${HS_BOX_POSTGRES_USERNAME:-hs}
      HS_BOX_POSTGRES_PASSWORD: ${HS_BOX_POSTGRES_PASSWORD:-example}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./services/postgres/entrypoint/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d db_user && pg_isready -U postgres -d db_cms && pg_isready -U postgres -d db_box_office" ]
      start_period: 60s
      interval: 10s
      timeout: 60s
      retries: 5

  liquibase-users:
    build:
      context: services/liquibase
      dockerfile: users.dockerfile
      args:
        BUNDLER_IMAGE: ${HS_USER_IMAGE:-mhws/hs-users:latest}
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      LIQUIBASE_COMMAND_USERNAME: ${HS_USER_POSTGRES_USERNAME:-hs}
      LIQUIBASE_COMMAND_PASSWORD: ${HS_USER_POSTGRES_PASSWORD:-example}
      LIQUIBASE_COMMAND_URL : jdbc:postgresql://postgres:5432/db_user
    command: --defaults-file=/liquibase/liquibase.properties update

  hs-users:
    image: ${HS_USER_IMAGE:-mhws/hs-users:latest}
    depends_on:
      liquibase-users:
        condition: service_completed_successfully
    environment:
      HS_USER_EUREKA_URI: http://eureka:8761/eureka
      HS_USER_DATASOURCE_HOST: postgres
      HS_USER_DATASOURCE_PORT: 5432
      HS_USER_DATASOURCE_DATABASE: db_user
      HS_USER_DATASOURCE_USERNAME: ${HS_USER_POSTGRES_USERNAME:-hs}
      HS_USER_DATASOURCE_PASSWORD: ${HS_USER_POSTGRES_PASSWORD:-example}
      HS_USER_JWT_SECRET_KEY: ${HS_USER_JWT_SECRET_KEY:-H3G7wpVdJNA9hsK4zaQm6uCUZqHLg2RFKs7D8M6J9mbf}
      HS_USER_JWT_EXPIRATION: ${HS_USER_JWT_EXPIRATION:-86400000}

  liquibase-cms:
    build:
      context: services/liquibase
      dockerfile: cms.dockerfile
      args:
        BUNDLER_IMAGE: ${HS_CMS_IMAGE:-mhws/hs-cms:latest}
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      LIQUIBASE_COMMAND_USERNAME: ${HS_CMS_POSTGRES_USERNAME:-hs}
      LIQUIBASE_COMMAND_PASSWORD: ${HS_CMS_POSTGRES_PASSWORD:-example}
      LIQUIBASE_COMMAND_URL : jdbc:postgresql://postgres:5432/db_cms
    command: --defaults-file=/liquibase/liquibase.properties update

  hs-cms:
    image: ${HS_CMS_IMAGE:-mhws/hs-cms:latest}
    depends_on:
      liquibase-cms:
        condition: service_completed_successfully
    environment:
      HS_CMS_EUREKA_URI: http://eureka:8761/eureka
      HS_CMS_DATASOURCE_HOST: postgres
      HS_CMS_DATASOURCE_PORT: 5432
      HS_CMS_DATASOURCE_DATABASE: db_cms
      HS_CMS_DATASOURCE_USERNAME: ${HS_CMS_POSTGRES_USERNAME:-hs}
      HS_CMS_DATASOURCE_PASSWORD: ${HS_CMS_POSTGRES_PASSWORD:-example}
      HS_CMS_HAZELCAST_ADDRESSES: hazelcast:5701
      HS_CMS_KAFKA_URI: kafka:9092

  liquibase-box:
    build:
      context: services/liquibase
      dockerfile: box-office.dockerfile
      args:
        BUNDLER_IMAGE: ${HS_BOX_IMAGE:-mhws/hs-box-office:latest}
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      LIQUIBASE_COMMAND_USERNAME: ${HS_BOX_POSTGRES_USERNAME:-hs}
      LIQUIBASE_COMMAND_PASSWORD: ${HS_BOX_POSTGRES_PASSWORD:-example}
      LIQUIBASE_COMMAND_URL : jdbc:postgresql://postgres:5432/db_box_office
    command: --defaults-file=/liquibase/liquibase.properties update

  hs-box:
    image: ${HS_BOX_IMAGE:-mhws/hs-box-office:latest}
    depends_on:
      liquibase-box:
        condition: service_completed_successfully
    environment:
      HS_BOX_OFFICE_EUREKA_URI: http://eureka:8761/eureka
      HS_BOX_OFFICE_DATASOURCE_HOST: postgres
      HS_BOX_OFFICE_DATASOURCE_PORT: 5432
      HS_BOX_OFFICE_DATASOURCE_DATABASE: db_box_office
      HS_BOX_OFFICE_DATASOURCE_USERNAME: ${HS_BOX_POSTGRES_USERNAME:-hs}
      HS_BOX_OFFICE_DATASOURCE_PASSWORD: ${HS_BOX_POSTGRES_PASSWORD:-example}

  hs-files:
    image: ${HS_FILES_IMAGE:-mhws/hs-files:latest}
    environment:
      HS_FILES_EUREKA_URI: http://eureka:8761/eureka
      HS_FILES_PAINTINGS_VOLUME: /pictures
      HS_FILES_HAZELCAST_ADDRESSES: hazelcast:5701
      HS_FILES_KAFKA_URI: kafka:9092
    volumes:
      - paintings:/paintings

  gateway:
    build:
      context: .
      dockerfile: dockerfile
    # image: ${HS_GATEWAY_IMAGE:-mhws/hs-gateway:latest}
    ports:
      - ${HS_GATEWAY_PORT:-8370}:8762
    environment:
      HS_GATEWAY_EUREKA_URI: http://eureka:8761/eureka

  hazelcast:
    image: hazelcast/hazelcast:5.3-slim
    environment:
      JAVA_OPTS: "-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.yaml"
    ports:
      - ${HS_HAZELCAST_PORT:-5701}:5701
    volumes:
      - ./services/hazelcast:/opt/hazelcast/config_ext

  kafka:
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "9092:9094"
    volumes:
      - "kafka-data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

volumes:
  postgres-data:
  paintings:
  kafka-data:
