server:
  port: 8762

eureka:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  client:
    service-url:
      defaultZone: ${HS_GATEWAY_EUREKA_URI:http://localhost:8375/eureka}

reactive:
  feign:
    circuit:
      breaker:
        enabled: false

spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

      routes:
        - id: users-auth
          uri: lb://users
          predicates:
            - Path=/api/v1/auth/**

        - id: users-users
          uri: lb://users
          predicates:
            - Path=/api/v1/users/**

        - id: users-openapi
          uri: lb://users
          predicates:
            - Path=/users/api-docs
          filters:
            - RewritePath=/users/(?<path>.*), /$\{path}

        - id: files-pictures-inner
          uri: lb://files
          predicates:
            - Path=/api/v1/paintings/{id}/files/**
          filters:
            - RewritePath=/api/v1/paintings/(?<id>.*)/files(?<rest>/.*)?, /api/v1/paintings/${id}${rest}
            - AuthFilter

        - id: files-openapi
          uri: lb://files
          predicates:
            - Path=/files/api-docs
          filters:
            - RewritePath=/files/(?<path>.*), /$\{path}

        - id: cms-artists
          uri: lb://cms
          predicates:
            - Path=/api/v1/artists/**
          filters:
            - AuthFilter

        - id: cms-exhibitions
          uri: lb://cms
          predicates:
            - Path=/api/v1/exhibitions/**
          filters:
            - AuthFilter

        - id: cms-galleries
          uri: lb://cms
          predicates:
            - Path=/api/v1/galleries/**
          filters:
            - AuthFilter

        - id: cms-paintings
          uri: lb://cms
          predicates:
            - Path=/api/v1/paintings/**
          filters:
            - AuthFilter
    
        - id: cms-recs
          uri: lb://cms
          predicates:
            - Path=/api/v1/recs/**
          filters:
            - AuthFilter

        - id: cms-openapi
          uri: lb://cms
          predicates:
            - Path=/cms/api-docs
          filters:
            - RewritePath=/cms/(?<path>.*), /$\{path}

        - id: box-office-orders
          uri: lb://box-office
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - AuthFilter

        - id: box-office-tickets
          uri: lb://box-office
          predicates:
            - Path=/api/v1/tickets/**
          filters:
            - AuthFilter

        - id: box-office-openapi
          uri: lb://box-office
          predicates:
            - Path=/box-office/api-docs
          filters:
            - RewritePath=/box-office/(?<path>.*), /$\{path}

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui"
    urls: # explicitly set urls to match gateway filters
      - url: /users/api-docs
        name: API Users microservice
      - url: /cms/api-docs
        name: API CMS microservice
      - url: /box-office/api-docs
        name: API Box Office microservice
      - url: /files/api-docs
        name: API Files microservice
      - url: api-docs
        name: API Gateway microservice

logging:
 level:
   reactor.netty: DEBUG
   org.springframework.cloud.gateway: DEBUG
   org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
   io.github.resilience4j: TRACE
