server:
  port: 8762

eureka:
  instance:
    appname: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  client:
    service-url:
      defaultZone: ${HS_GATEWAY_EUREKA_URI:http://localhost:8761/eureka}

reactive:
  feign:
    circuit:
      breaker:
        enabled: false

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: trace
    io.github.resilience4j: debug

spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://user
          predicates:
            - Path=/api/v1/auth/**

        - id: user
          uri: lb://user
          predicates:
            - Path=/api/v1/users/**

        - id: artists
          uri: lb://cms
          predicates:
            - Path=/api/v1/artists/**
          filters:
            - AuthFilter

        - id: exhibitions
          uri: lb://cms
          predicates:
            - Path=/api/v1/exhibitions/**
          filters:
            - AuthFilter

        - id: galleries
          uri: lb://cms
          predicates:
            - Path=/api/v1/galleries/**
          filters:
            - AuthFilter

        - id: paintings
          uri: lb://cms
          predicates:
            - Path=/api/v1/paintings/**
          filters:
            - AuthFilter
    
        - id: recs
          uri: lb://cms
          predicates:
            - Path=/api/v1/recs/**
          filters:
            - AuthFilter

# logging:
#   level:
#     org.springframework.cloud.gateway: DEBUG
#     reactor.netty.http.client: DEBUG
