server:
  port: 8762

eureka:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  client:
    service-url:
      defaultZone: ${HS_GATEWAY_EUREKA_URI:http://localhost:8761/eureka}

reactive:
  feign:
    circuit:
      breaker:
        enabled: false

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: users-auth
          uri: lb://users
          predicates:
            - Path=/api/v1/auth/**

        - id: users-users
          uri: lb://users
          predicates:
            - Path=/api/v1/users/**

        - id: users-openapi
          uri: lb://users
          predicates:
            - Path=/users/api-docs
          filters:
            - RewritePath=/users/(?<path>.*), /$\{path}

        - id: cms-artists
          uri: lb://cms
          predicates:
            - Path=/api/v1/artists/**
          filters:
            - AuthFilter

        - id: cms-exhibitions
          uri: lb://cms
          predicates:
            - Path=/api/v1/exhibitions/**
          filters:
            - AuthFilter

        - id: cms-galleries
          uri: lb://cms
          predicates:
            - Path=/api/v1/galleries/**
          filters:
            - AuthFilter

        - id: cms-paintings
          uri: lb://cms
          predicates:
            - Path=/api/v1/paintings/**
          filters:
            - AuthFilter
    
        - id: cms-recs
          uri: lb://cms
          predicates:
            - Path=/api/v1/recs/**
          filters:
            - AuthFilter

        - id: cms-openapi
          uri: lb://cms
          predicates:
            - Path=/cms/api-docs
          filters:
            - RewritePath=/cms/(?<path>.*), /$\{path}

        - id:
          uri: lb://box-office
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - AuthFilter

        - id:
          uri: lb://box-office
          predicates:
            - Path=/api/v1/tickets/**
          filters:
            - AuthFilter

        - id: cms-openapi
          uri: lb://box-office
          predicates:
            - Path=/box-office/api-docs
          filters:
            - RewritePath=/box-office/(?<path>.*), /$\{path}

# logging:
#   level:
#     org.springframework.cloud.gateway: DEBUG
#     reactor.netty.http.client: DEBUG
#    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: trace
#    io.github.resilience4j: debug

